language: elixir

elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.0

node_js:
  - "6"
  - "8"
  - "10"

otp_release:
  - 20.0
  - 21.2

env:
  global:
    - MIX_ENV=test

before_script:
  - npm install -g aglio

script:
  - mix do deps.get, deps.compile, coveralls.travis
