language: elixir

matrix:
  include:
    - opt_release: 18.0
      elixir: 1.3
    - opt_release: 18.0
      elixir: 1.4
    - opt_release: 19.0
      elixir: 1.3
    - opt_release: 19.0
      elixir: 1.4
sudo: false

env:
  - MIX_ENV=test

before_script:
  - mix deps.get

script:
  - mix credo
  - mix coveralls.travis
