language: elixir

elixir:
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - 1.4.0
  - 1.4.1
  - 1.4.2

otp_release:
  - 18
  - 19

env:
  global:
    - MIX_ENV=test

script:
  - mix do deps.get, deps.compile, coveralls.travis
