language: elixir

elixir:
  - 1.4.0
  - 1.4.1
  - 1.4.2
  - 1.5.1

node_js:
  - "6"
  - "7"
  - "8"

otp_release:
  - 19.0
  - 19.1
  - 19.2
  - 19.3
  - 20.0

env:
  global:
    - MIX_ENV=test

before_script:
  - npm install -g aglio

script:
  - mix do deps.get, deps.compile, coveralls.travis
